language: node_js
sudo: false
node_js:
- 8
- 9
- 10

script:
- npm run test && codecov

before_deploy:
- npm --no-git-tag-version version `git describe --tags` 2>/dev/null || true

deploy:
  provider: npm
  skip_cleanup: true
  email: oopinou@gmail.com
  api_key:
    secure: C3TUZlRdko/sk5SMjUWBfGDn/2GiJFrLqSFPCUkBIZw13rVKai+VaaPsYBunrhZC/isjYDgNr0dCAig7xMDwf88jwAkxYMz/zsxNMDe8kJW7XxRSCvPXZI29xK+LWsfRHeS4UxYm6/aCEZeFO9kQlXLAW/4DRiTLCgFeQEGPfHdLkxfCubnjXL2UThp65x8RDdVqYiHC6vN90l+poKi6b4puBoCxaTIssPrJ4vnQIK+lRQs0XckNhCsH6A/ECb9+e3JLvxUYdxXsnAtxdgf/ulfk6HESSMaRXB1j/5VCFBAv7qPtUBF769ZSXzUgxYwwK5gU0/sgVLQRGmEU7p5DVNw5+0iE2CMlHx0oazavee/dCT/ZoTEt7aYql872mtIyNyVzKkOu4yYdpA2rWbTNYIH8H6kfKY1Ue+0G5WyKzzz7ZsxgU05qhWNbOCFP6OncCm5F2OVVOZDtmvs10XthqFGqiUzJY9xFtF746aIKB8tiXO4gntBJTcVA7yI7Mi1rJFi6x3Pa+JHEHe8Jl4FYk3p8tpJH6Dvyi5k3LMHxz7v2y9PNeHuEKeJ+wPaKzrOShTZWxlCCWThnqfSdUoNqvbU6sV3Tyk8l30SCGcqdIIJZYibC8fozN1APgE3Euld1i+TRnNHKD+EGeEBoSlygieKTcpfnrFEUsvOFJNBEork=
  on:
    tags: true
    repo: DavidBabel/vast-builder
