language: node_js
sudo: false
node_js:
  - 8
  - 10
  - 11
  - 12

install:
  - yarn install

script:
  - yarn circular-dependencies
  - yarn outdated || true
  - yarn depcheck
  - yarn test && codecov
  - yarn build-ts

before_deploy:
  - npm --no-git-tag-version version `git describe --tags` 2>/dev/null || true
  - yarn install --production --ignore-scripts --prefer-offline

deploy:
  provider: npm
  skip_cleanup: true
  email: oopinou@gmail.com
  api_key:
    secure: n1mIGmp+SGJ2jaCrj/vSQ1ME3BaOwiFkkY8ChPJv39b3vYXeX3QEq1JuF1Nh+nO0B3Z85oZIKRPdIToY1lByNVeCUh3YawQz8iL2O8JbUgE49N3A68WYnykMfZJXCUf4dziPTMNG9oMRzEOkWONzji/ZTVLgFhMcmP7uMgqA4GeWmyX4u4AalROc4brJ6qWNTrJ4J9mlEhDs+3U+1Oj2872xV2XJRcVCZ1nqljE/0FzuZU4sTkzpmq5AiJFn85ilJMa41MfAiLr3Ll0jSxCyRgMUOCWcjt3EczAc6DjY1IfuKh5SSay5mOVuf1kgx6IFqJ+683NLHCqJ+XrBZ0Gujx1AxN9stCuH+G2Dt9jiOqRcC0MAtKnZC2cKJkl//qfswB7oh4FqdC2TKgR3WvMD5FZ0tRY3+riob7ZrOLGuYUAQDnZ0MmQMJIHmnGT0QPB1M9kqnQiyH5q3lssQUW59CAJFfTAlrgeosoMXJhmTBUrRYXhkMWjmgLdijTjCCOSVmy03d0CiiRpSubVFxh2m/ZF5yBJqZRvb6tcrvq0zaxKbZlnal2NfHXADqqAO8ChYorpapaEKwgAfcUK4JOT6YWSuZfK8VICMfw7NUlPc2enMvSpY3wMhDdAGcK916LlH1KU13BHpKdWl0syXVrgARXAktwNkZobANgEjsNbZp98=
  on:
    tags: true
    repo: DavidBabel/vast-library
